// Code generated by type-wrapper; DO NOT EDIT.
package test

import (
	"github.com/Marble-Technologies/type-wrapper/cmd/testdata/import_packages/sub1"
	"github.com/Marble-Technologies/type-wrapper/cmd/testdata/import_packages/sub2"
	"github.com/Marble-Technologies/type-wrapper/cmd/testdata/import_packages/sub3"
	"time"
)

// TesterWrapper encapulates the type Tester
type TesterWrapper struct {
	Tester
}

func (t TesterWrapper) Field1() time.Time {
	return t.Tester.field1
}

func (t TesterWrapper) SetField1(val time.Time) {
	t.Tester.field1 = val
}

func (t TesterWrapper) Field2() *sub1.SubTester {
	return t.Tester.field2
}

func (t TesterWrapper) SetField2(val *sub1.SubTester) {
	t.Tester.field2 = val
}

func (t TesterWrapper) Field3() *sub2.SubTester {
	return t.Tester.field3
}

func (t TesterWrapper) SetField3(val *sub2.SubTester) {
	t.Tester.field3 = val
}

func (t TesterWrapper) Field4() *sub3.SubTester {
	return t.Tester.field4
}

func (t TesterWrapper) SetField4(val *sub3.SubTester) {
	t.Tester.field4 = val
}

