// Code generated by type-wrapper; DO NOT EDIT.
package test

// TesterWrapper encapulates the type Tester
type TesterWrapper struct {
	Tester
}

func (t TesterWrapper) SetField1(val string) {
	t.Tester.field1 = val
}

func (t TesterWrapper) SetSecondField(val int32) {
	t.Tester.field2 = val
}

