// Code generated by type-wrapper; DO NOT EDIT.
package test

import (
	"encoding/json"
)

type ITester interface {
	GetField1() string
	SetField1(val string)
	GetField2() int32
	SetField2(val int32)
	Read(p []byte) (int, error)
}

// TesterWrapper encapulates the type Tester
type TesterWrapper struct {
	// The name of the original type, it gets initalized when calling Read() function, DO NOT USE IT
	DataType string `json:"_data_type,omitempty"`
	Tester
}

func (t TesterWrapper) GetField1() string {
	t.lock.Lock()
	defer t.lock.Unlock()
	return t.Tester.field1
}

func (t TesterWrapper) SetField1(val string) {
	t.lock.Lock()
	defer t.lock.Unlock()
	t.Tester.field1 = val
}

func (t TesterWrapper) GetField2() int32 {
	t.lock.Lock()
	defer t.lock.Unlock()
	return t.Tester.field2
}

func (t TesterWrapper) SetField2(val int32) {
	t.lock.Lock()
	defer t.lock.Unlock()
	t.Tester.field2 = val
}

func (t TesterWrapper) Read(p []byte) (int, error) {
	t.lock.Lock()
	defer t.lock.Unlock()
	t.DataType = "Tester"
	data, err := json.Marshal(t)
	if err != nil {
		return 0, err
	}
	n := copy(p, data)
	return n, nil
}

