// Code generated by type-wrapper; DO NOT EDIT.
package test

// TesterWrapper encapulates the type Tester
type TesterWrapper struct {
	Tester
}

func (t TesterWrapper) Field1() string {
	return t.Tester.Field1
}

func (t TesterWrapper) SetField1(val string) {
	t.Tester.Field1 = val
}

func (t TesterWrapper) GetSecondField() int32 {
	return t.Tester.Field2
}

