// Code generated by type-wrapper; DO NOT EDIT.
package test

// TesterWrapper encapulates the type Tester
type TesterWrapper struct {
	Tester
}

func (t TesterWrapper) Field2() int32 {
	return t.Tester.field2
}

