// Code generated by type-wrapper; DO NOT EDIT.
package test

// TesterWrapper encapulates the type Tester
type TesterWrapper struct {
	Tester
}

func (t TesterWrapper) Field1() string {
	return t.Tester.field1
}

func (t TesterWrapper) SetSecondField(val int32) {
	t.Tester.field2 = val
}

