// Code generated by type-wrapper; DO NOT EDIT.
package test

// TesterWrapper encapulates the type Tester
type TesterWrapper struct {
	Tester
}

func (t TesterWrapper) GetField1() string {
	t.lock.Lock()
	defer t.lock.Unlock()
	return t.Tester.field1
}

func (t TesterWrapper) SetField1(val string) {
	t.lock.Lock()
	defer t.lock.Unlock()
	t.Tester.field1 = val
}

func (t TesterWrapper) GetField2() int32 {
	t.lock.Lock()
	defer t.lock.Unlock()
	return t.Tester.field2
}

func (t TesterWrapper) SetField2(val int32) {
	t.lock.Lock()
	defer t.lock.Unlock()
	t.Tester.field2 = val
}

