// Code generated by type-wrapper; DO NOT EDIT.
package test

// TesterWrapper encapulates the type Tester
type TesterWrapper struct {
	Tester
}

func (tester TesterWrapper) Field1() string {
	return tester.Tester.field1
}

func (tester TesterWrapper) SetSecondField(val int32) {
	tester.Tester.field2 = val
}

